version: 2

sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        idenifier: raw_listings

      - name: hosts
        idenifier: raw_hosts

      - name: reviews
        idenifier: raw_review
        loaded_at_field: date
        freshness:
          warn_after: {count: 1, period: hour}
          error_after: {count: 24, period: hour}
