version: 2

sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        idenifier: raw_listings
        columns:
          - name: room_type
            tests: 
              - dbt_expectactions.expect_column_distinct_count_to_equal:
                  value: 4
          - name: price
            tests:
              - dbt_expectactions.expect_column_values_to_match_regex:
                  regex: "^\\\\$[0-9][0-9\\\\.]+$"
      - name: hosts
        idenifier: raw_hosts

      - name: reviews
        idenifier: raw_review
        loaded_at_field: date
        freshness:
          warn_after: {count: 1, period: hour}
          error_after: {count: 24, period: hour}
